language: php

services:
    - mysql

php:
    - 7.2
    - 7.3
    - 7.4
    - nightly

# run build against nightly but allow them to fail
matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: COVERAGE=run
        - php: 7.2
          env: CS_FIXER=run
    allow_failures:
        - php: 7.4
        - php: nightly

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - composer self-update

before_script:
    - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
    - if [ $COVERAGE = run ]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi;

script:
    - make prepare
    - mkdir -p build/logs
    - php bin/simple-phpunit -v $PHPUNIT_FLAGS
    - if [ "$CS_FIXER" = "run" ]; then php bin/php-cs-fixer fix --verbose --dry-run ; fi;
    - if [ "$CS_FIXER" = "run" ]; then php bin/phpstan analyse src tests --no-progress --level 7 ; fi;

after_script:
    - |
        if [ $COVERAGE = run ]; then
            php bin/php-coveralls -v -x build/logs/clover.xml
        fi
