version: '2'
services:
  db:
    image: mariadb:10
    ports:
      - "57017:27017"
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  nginx-php7.2:
    build:
      context: ./docker
      dockerfile: ./Dockerfile-php7.2
    ports:
      - "58100:8100"
    links:
      - db
    volumes:
      - ./:/usr/share/nginx/html
    command: ["bash", "/usr/share/nginx/html/docker/launch-f43me.sh"]
