imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi: ~
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: v20151203
        version_format: '%%s?version=%%s'
        base_path: ~
    default_locale:  "%locale%"
    session:
        name: f43me
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: "%google_analytics_code%"

doctrine_mongodb:
    connections:
        default:
            server: "%database_server%"
            options: {}
    default_database: "%database_name%"
    document_managers:
        default:
            auto_mapping: true
            metadata_cache_driver:
                type: array

stof_doctrine_extensions:
    default_locale: en_US

    mongodb:
        default:
            timestampable: true
            sluggable: true

monolog:
    channels: ['import', 'graby']
    handlers:
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: DEBUG
            channels: import
            formatter: monolog.import.formatter
        graby:
            type: service
            id: graby.log_handler
            level: debug
            channels: ['graby']

# see https://github.com/symfony/symfony-standard/pull/1133
sensio_framework_extra:
   router:
        annotations: false

httplug:
    clients:
        default:
            factory: 'httplug.factory.guzzle6'
            config:
                defaults:
                    timeout: 30
                    proxy: 'http://localhost:8079' 
            http_methods_client: true
            plugins:
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.logger'
                - 'httplug.plugin.error'
                - header_defaults:
                    headers:
                        'User-Agent': f43.me/1.0
    discovery:
        client: false
