imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi: ~
    translator: { fallback: "%locale%" }
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: v20151203
        version_format: '%%s?version=%%s'
        base_path: ~
    default_locale:  "%locale%"
    session:
        name: f43me
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: ~
    http_method_override: true

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        ga_tracking: "%google_analytics_code%"

doctrine:
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: utf8mb4
        server_version: 5.7
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                dql:
                    datetime_functions:
                        DATE: DoctrineExtensions\Query\Mysql\Date

doctrine_migrations:
    dir_name: "%kernel.root_dir%/migrations"
    name: f43 Migrations

stof_doctrine_extensions:
    default_locale: en_US

    orm:
        default:
            sluggable: true

monolog:
    channels: ['import', 'graby']
    handlers:
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: DEBUG
            channels: import
            formatter: monolog.import.formatter
        graby:
            type: service
            id: graby.log_handler
            level: info
            channels: ['graby']

# see https://github.com/symfony/symfony-standard/pull/1133
sensio_framework_extra:
   router:
        annotations: false

httplug:
    clients:
        default:
            factory: 'httplug.factory.guzzle6'
            config: # distinguished from wallabag http factory, no need for {"defaults": ..
                timeout: 30
                proxy: 'http://127.0.0.1:8118' 
            http_methods_client: true
            plugins:
                - 'httplug.plugin.redirect'
                - 'httplug.plugin.logger'
                - 'httplug.plugin.error'
                - header_defaults:
                    headers:
                        'User-Agent': f43.me/1.0
    discovery:
        client: false

swarrot:
    provider: amqp_lib # pecl or amqp_lib
    connections:
        rabbitmq:
            host: '%rabbitmq_host%'
            port: '%rabbitmq_port%'
            login: '%rabbitmq_login%'
            password: '%rabbitmq_password%'
            vhost: '/'
    consumers:
        f43.fetch_items:
            processor: AppBundle\Consumer\FetchItems
            extras:
                poll_interval: 500000
            middleware_stack:
                - configurator: swarrot.processor.max_messages
                  extras:
                      max_messages: 20
                - configurator: swarrot.processor.doctrine_connection
                - configurator: swarrot.processor.retry
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
    messages_types:
        f43.fetch_items.publisher:
            connection: rabbitmq
            exchange: f43.fetch_items
