services:
    # feed extractor
    AppBundle\Extractor\ExtractorChain:
        class: AppBundle\Extractor\ExtractorChain

    feed.extractor.imgur:
        class: AppBundle\Extractor\Imgur
        arguments:
            - "@imgur.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: imgur }

    feed.extractor.twitter:
        class: AppBundle\Extractor\Twitter
        arguments:
            - "@twitter.client"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: twitter }

    feed.extractor.tumblr:
        class: AppBundle\Extractor\Tumblr
        arguments:
            - "%tumblr.api_key%"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: tumblr }

    feed.extractor.vine:
        class: AppBundle\Extractor\Vine
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vine }

    feed.extractor.instagram:
        class: AppBundle\Extractor\Instagram
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: instagram }

    feed.extractor.vidme:
        class: AppBundle\Extractor\Vidme
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vidme }

    feed.extractor.gfycat:
        class: AppBundle\Extractor\Gfycat
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: gfycat }

    feed.extractor.flickr:
        class: AppBundle\Extractor\Flickr
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: flickr }

    #feed.extractor.github:
    #    class: AppBundle\Extractor\Github
    #    arguments:
    #        - "%github.client_id%"
    #        - "%github.client_secret%"
    #    calls:
    #        - [ setLogger, [ "@logger" ]]
    #        - [ setClient, [ "@httplug.client.default.http_methods" ]]
    #    tags:
    #        -  { name: feed.extractor, alias: github }

    feed.extractor.deviantart:
        class: AppBundle\Extractor\Deviantart
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: deviantart }

    feed.extractor.camplus:
        class: AppBundle\Extractor\Camplus
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: camplus }

    feed.extractor.soundcloud:
        class: AppBundle\Extractor\Soundcloud
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: soundcloud }

    feed.extractor.vimeo:
        class: AppBundle\Extractor\Vimeo
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: vimeo }

    feed.extractor.youtube:
        class: AppBundle\Extractor\Youtube
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: youtube }

    feed.extractor.dailymotion:
        class: AppBundle\Extractor\Dailymotion
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: dailymotion }

    feed.extractor.spotify:
        class: AppBundle\Extractor\Spotify
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: spotify }

    feed.extractor.hackernews:
        class: AppBundle\Extractor\HackerNews
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: hackernews }

    feed.extractor.rue89:
        class: AppBundle\Extractor\Rue89
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: rue89 }

    feed.extractor.streamable:
        class: AppBundle\Extractor\Streamable
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: streamable }

    feed.extractor.ifttt:
        class: AppBundle\Extractor\Ifttt
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: ifttt }

    feed.extractor.redditimage:
        class: AppBundle\Extractor\RedditImage
        calls:
            - [ setLogger, [ "@logger" ]]
        tags:
            -  { name: feed.extractor, alias: redditimage }

    feed.extractor.redditvideo:
        class: AppBundle\Extractor\RedditVideo
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: redditvideo }

    feed.extractor.redditpost:
        class: AppBundle\Extractor\RedditPost
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: redditpost }

    feed.extractor.giphy:
        class: AppBundle\Extractor\Giphy
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: giphy }

    feed.extractor.twitch:
        class: AppBundle\Extractor\Twitch
        arguments:
            - "%twitch.client_id%"
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: twitch }

    feed.extractor.periscope:
        class: AppBundle\Extractor\Periscope
        calls:
            - [ setLogger, [ "@logger" ]]
            - [ setClient, [ "@httplug.client.default.http_methods" ]]
        tags:
            -  { name: feed.extractor, alias: periscope }
